Fix compilation of set proto calls
The setter functions were added in OpenSSL 1.1.0 [1]. The patch fixes
compilation for previous versions:

/usr/bin/ld: $WORK/b079/_x030.o: in function `X_SSL_CTX_set_min_proto_version':
./shim.c:479: undefined reference to `SSL_CTX_set_min_proto_version'
/usr/bin/ld: $WORK/b079/_x030.o: in function `X_SSL_CTX_set_max_proto_version':
./shim.c:483: undefined reference to `SSL_CTX_set_max_proto_version'

1. https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_min_proto_version.html